(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(git-gutter:handled-backends (quote (svn hg git)))
 '(package-selected-packages
   (quote
    (zerodark-theme nord-theme atom-dark-theme zenburn-theme zen-and-art-theme white-sand-theme underwater-theme ujelly-theme twilight-theme twilight-bright-theme twilight-anti-bright-theme toxi-theme tao-theme tangotango-theme tango-plus-theme tango-2-theme sunny-day-theme sublime-themes subatomic256-theme subatomic-theme spacemacs-theme spacegray-theme soothe-theme solarized-theme soft-stone-theme soft-morning-theme soft-charcoal-theme smyx-theme seti-theme reverse-theme rebecca-theme railscasts-theme purple-haze-theme professional-theme planet-theme phoenix-dark-pink-theme phoenix-dark-mono-theme organic-green-theme omtose-phellack-theme oldlace-theme occidental-theme obsidian-theme noctilux-theme naquadah-theme mustang-theme monokai-theme monochrome-theme molokai-theme moe-theme minimal-theme material-theme majapahit-theme madhat2r-theme lush-theme light-soap-theme leuven-theme kaolin-themes jbeans-theme jazz-theme ir-black-theme inkpot-theme heroku-theme hemisu-theme hc-zenburn-theme gruvbox-theme gruber-darker-theme grandshell-theme gotham-theme gandalf-theme flatui-theme flatland-theme farmhouse-theme eziam-theme exotica-theme espresso-theme dracula-theme doom-themes django-theme darktooth-theme darkokai-theme darkmine-theme darkburn-theme dakrone-theme cyberpunk-theme color-theme-sanityinc-tomorrow color-theme-sanityinc-solarized clues-theme cherry-blossom-theme busybee-theme bubbleberry-theme birds-of-paradise-plus-theme yasnippet-snippets yaml-mode writeroom-mode workgroups2 winum wgrep web-mode w3m visual-regexp vimrc-mode unfill typescript-mode toc-org textile-mode tagedit slime simple-httpd shackle session scss-mode scratch rvm rust-mode rjsx-mode request regex-tool rainbow-delimiters pyim-basedict pomodoro paredit package-lint nvm nov neotree multi-term magit lua-mode lsp-mode legalese langtool keyfreq jump jss js-doc jade-mode ivy-hydra ibuffer-vc htmlize haml-mode groovy-mode gnu-elpa-keyring-update gitignore-mode gitconfig-mode git-timemachine git-link gist fringe-helper flymake-lua flymake-jslint find-file-in-project find-by-pinyin-dired expand-region exec-path-from-shell evil-visualstar evil-textobj-syntax evil-surround evil-nerd-commenter evil-matchit evil-mark-replace evil-lion evil-iedit-state evil-find-char-pinyin evil-exchange evil-escape evil-args emms emmet-mode elpy elpa-mirror dumb-jump dsvn diredfl diminish dictionary csv-mode cpputils-cmake counsel-gtags counsel-css counsel-bbdb company-statistics company-c-headers command-log-mode color-theme cmake-mode cliphist buffer-move benchmark-init bbdb bash-completion base16-theme badwolf-theme auto-yasnippet auto-package-update atom-one-dark-theme apropospriate-theme anti-zenburn-theme amx ample-zen-theme ample-theme alect-themes afternoon-theme adoc-mode ace-window ace-link)))
 '(session-use-package t nil (session)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
